import imagesFolder from '../assets/**/*.jpg'
// Following line is a test to check what happens when no images are found
// import imagesFolder from '../assets/**/*.png'

// imageKeys is an array of the object keys generated by Parcel's import of the images folder
// images is a data structure containining, for each imageKey, a file path to be injected in the DOM, and a view counter to keep track of the number of times each image is being displayed
const images = {}
let imageKeys

if (imagesFolder?.images) {
  imageKeys = Object.keys(imagesFolder.images)

  for (const [key, value] of Object.entries(imagesFolder.images)) {
    images[key] = {
      path: value,
      viewCounter: 0
    }
  }
} else {
  imageKeys = []
}

const initialState = {
  imageKeys: imageKeys,
  images: images
}

export default initialState
